# Generated by Django 4.2.3 on 2023-08-20 22:18

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedvideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(verbose_name='Embed Video'),
        ),
    ]
