# Generated by Django 4.2.4 on 2023-08-26 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_lecture_is_final_alter_lecture_is_midterm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='video id used on Vimeo', max_length=200, verbose_name='Video ID')),
                ('title', models.CharField(help_text='e.g. Week 1 Video', max_length=200, verbose_name='Title of Video')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecture', verbose_name='Lecture')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
        ),
    ]
