# Generated by Django 4.2.4 on 2023-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimeovideo',
            name='video_id',
            field=models.CharField(help_text='video id used on Vimeo', max_length=200, null=True, verbose_name='Video ID'),
        ),
    ]
