# Generated by Django 4.2.4 on 2023-08-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_vimeovideo_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimeovideo',
            name='video_id',
            field=models.CharField(help_text='"/videos/video_id", from address bar of browser', max_length=200, null=True, verbose_name='Video URI'),
        ),
    ]
