# Generated by Django 4.2.4 on 2023-08-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_vimeovideo_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vimeovideo',
            name='video_id',
        ),
        migrations.AddField(
            model_name='vimeovideo',
            name='uri',
            field=models.CharField(help_text='video id used on Vimeo', max_length=200, null=True, verbose_name='Video ID'),
        ),
    ]
