# Generated by Django 4.2.4 on 2023-09-05 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lecture_is_final_alter_lecture_is_midterm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0004_remove_vimeovideo_video_id_vimeovideo_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimeovideo',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lecture', verbose_name='Lecture'),
        ),
        migrations.AlterField(
            model_name='vimeovideo',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='vimeovideo',
            name='uri',
            field=models.CharField(help_text='"/videos/xxxxxxxxx" from address bar of video', max_length=200, null=True, verbose_name='Video URI'),
        ),
    ]
