# Generated by Django 4.2.4 on 2023-09-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_vimeovideo_lecture_alter_vimeovideo_uploader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vimeovideo',
            name='max_num_watch',
            field=models.PositiveIntegerField(default=2, help_text='Max number of times that a student can watch this video', verbose_name='Watching Limit'),
        ),
    ]
