# Generated by Django 4.2.3 on 2023-08-13 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollments',
            new_name='Enrollment',
        ),
    ]
