# Generated by Django 4.2.4 on 2023-09-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='nums_watched',
            field=models.JSONField(default=dict, help_text='Dictionary of times of watching on each video', verbose_name='Times Watched'),
        ),
    ]
