# Generated by Django 4.2.4 on 2023-09-09 01:11

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_enrollment_nums_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='nums_watched',
            field=models.JSONField(default=students.models.json_default_dict, help_text='Dictionary of times of watching on each video', verbose_name='Times Watched'),
        ),
    ]
