# Generated by Django 4.2.4 on 2023-09-07 02:25

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_lecture_is_final_alter_lecture_is_midterm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Week 1 notes', max_length=200, verbose_name='Title of notes')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload time')),
                ('document', models.FileField(upload_to=notes.models.get_upload_to, verbose_name='Document to be uploaded')),
                ('lecture', models.ForeignKey(help_text='Lecture corresponds to this notes', on_delete=django.db.models.deletion.CASCADE, to='courses.lecture', verbose_name='Lecture')),
            ],
        ),
    ]
