# Generated by Django 4.2.3 on 2023-08-11 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_term_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('APBI', 'APBI'), ('APSC', 'APSC'), ('BIOL', 'BIOL'), ('CHEM', 'CHEM'), ('COMM', 'COMM'), ('COMR', 'COMR'), ('CPEN', 'CPEN'), ('CPSC', 'CPSC'), ('DCSI', 'DCSI'), ('ECON', 'ECON'), ('ELEC', 'ELEC'), ('EOSC', 'EOSC'), ('MATH', 'MATH'), ('MFRE', 'MFRE'), ('PHIL', 'PHIL'), ('PHYS', 'PHYS'), ('PSYC', 'PSYC'), ('SCIE', 'SCIE'), ('STAT', 'STAT'), ('VANT', 'VANT'), ('WRDS', 'WRDS')], help_text='Subject code, e.g. ECON.', max_length=4, verbose_name='Subject')),
                ('course_number', models.CharField(help_text='3-digits course number, e.g. 101.', max_length=3, verbose_name='Course Number')),
                ('section', models.CharField(blank=True, help_text='Section number, e.g. 202 or professor name. <strong>Leave it blank</strong> if there is only one section.', max_length=20, verbose_name='Section')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.term', verbose_name='Term')),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'is_tutor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
        ),
    ]
