# Generated by Django 4.2.3 on 2023-08-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Enter the title of the lecture, e.g. Math101 Lecture 1.', max_length=300, verbose_name='Title')),
                ('week', models.PositiveIntegerField(help_text='Enter the week number.', verbose_name='Week No.')),
                ('syllabus', models.TextField(blank=True, help_text='A short syllabus of this lecture.')),
                ('is_midterm', models.BooleanField(default=False, help_text='Is this a midterm review lecture? (是否为期中冲刺)', verbose_name='Midterm Review?')),
                ('is_final', models.BooleanField(default=False, help_text='Is this a final review lecture? (是否为期末冲刺)', verbose_name='Final Review?')),
                ('is_public', models.BooleanField(default=False, help_text='Is this a free sample lecture? (是否为试听课)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('course', models.ForeignKey(help_text='Select the course.', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
            ],
        ),
    ]
