# Generated by Django 4.2.4 on 2023-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Is this a final review lecture? (是否为期末冲刺)', verbose_name='Final Review'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_midterm',
            field=models.BooleanField(default=False, help_text='Is this a midterm review lecture? (是否为期中冲刺)', verbose_name='Midterm Review'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Is this a free sample lecture? (是否为试听课)', verbose_name='Free Sample'),
        ),
    ]
